### PR TITLE
Fixed rebasing for #34

### LINKED ISSUE #22: Add feature for GitHub key update
On first login itself, the user would be provided with a prompt to set up their GitHub public key.

It could be something like

``` bash
To make pushing code to GitHub easier, we would go ahead and setup your GitHub access keys now. Would you like to proceed? Type (Y)es or (N)o.
```

If user says `No`, or hits <kbd>n</kbd> or <kbd>N</kbd>, skip the process. Print out how you can do this in the future by maybe running some command.

If user just hits <kbd>Enter</kbd> or <kbd>Y</kbd> + <kbd>Enter</kbd>; go ahead and ask for email ID. If it's not a valid email ID, or GitHub returns some error saying ID not found; ask again. Do this in a loop.

If user hits <kbd>Ctrl + C</kbd> or <kbd>Cmd + C</kbd>; just print a prompt asking if they are sure they want to exit. We need this to set some value in some hidden file to ensure we don't bother the user again on next login.

If everything works successfully, clearly print out what file you changed, and how the user can now push to his repos with just command without any password.

### PR DESCRIPTION
**Pull request by abhisekp**
Rebased and resolved conflicts in #34 

Closes #34 
Closes #22

### CODE REVIEW

**Comment by byteknacker** [comment]
Thanks so much for that!!

**Comment by byteknacker** [comment]
I think we still need to sort out the conflict

**Comment by abhisekp** [comment]
@byteknacker umm... there are conflicts :pens

**Comment by abhisekp** [comment]
@alayek @byteknacker please test :+1:

File: provision.sh [hunk 1]
```diff
@@ -71,10 +71,23 @@ echo "---------------------------------------------"
 su - vagrant -c "/usr/local/bin/virtualenv /home/vagrant/.virtualenvs/${ENV_NAME} --python=/usr/bin/python3 && \
     /home/vagrant/.virtualenvs/${ENV_NAME}/bin/pip install -r /vagrant/requirements.txt"
 
+<<<<<<< HEAD
```
Comment (alayek) [inline provision.sh]: Remove this

File: provision.sh [hunk 2]
```diff
@@ -71,10 +71,23 @@ echo "---------------------------------------------"
...
 su - vagrant -c "cp /vagrant/.bashrc /home/vagrant/.bashrc"
 # If you are on Windows host, with Git checkout windows line terminator style CRLF
 # this comes in handy
 su - vagrant -c "dos2unix  /home/vagrant/.bashrc > /dev/null 2>&1"
+=======
+<<<<<<< HEAD
```
Comment (alayek) [inline provision.sh]: Remove this.

File: provision.sh [hunk 3]
```diff
@@ -71,10 +71,23 @@ echo "---------------------------------------------"
...
+su - vagrant -c "cp /vagrant/.bashrc /home/vagrant/.bashrc" 
+=======
+su - vagrant -c "cp /vagrant/.bashrc /home/vagrant/"
+su - vagrant -c "mkdir /home/vagrant/.configs"
+su - vagrant -c "cp /vagrant/zeus.sh /home/vagrant/.configs/zeus"
+# If you are on Windows host, with Git checkout windows line terminator style CRLF
+# this comes in handy
+su - vagrant -c "dos2unix  /home/vagrant/.bashrc > /dev/null 2>&1"
+>>>>>>> c9e0e91... Add feature of git config setup via user input
```
Comment (alayek) [inline provision.sh]: Remove this.

File: provision.sh [hunk 4]
```diff
@@ -71,10 +71,23 @@ echo "---------------------------------------------"
...
+>>>>>>> 751d888... Add feature of git config setup via user input
```
Comment (alayek) [inline provision.sh]: Remove this.

File: provision.sh [hunk 5]
```diff
@@ -38,7 +38,7 @@ echo "---------------------------------------------"
 # And that would prevent ~/.bashrc to work properly because \r would be unrecognized
 # Ruby needed for heroku toolbelt
 # notice that this is not a rigorous Ruby install, where we typically use rvm
-apt-get install -y --no-install-recommends heroku-toolbelt build-essential dos2unix python-pip man ruby python-dev python3-dev libpq-dev postgresql postgresql-contrib 
+apt-get install -y --no-install-recommends heroku-toolbelt build-essential dos2unix python-pip man ruby python-dev python3-dev libpq-dev postgresql postgresql-contrib curl
```
Comment (alayek) [inline provision.sh]: @koustuvsinha The `libpython2.7-dev` package takes up 22.0 MB in download, but we don't even use it because we are using Python 3 with postgreSQL. Should we remove it?

File: provision.sh [hunk 6]
```diff
@@ -71,10 +71,23 @@ echo "---------------------------------------------"
...
 
+<<<<<<< HEAD
 su - vagrant -c "cp /vagrant/.bashrc /home/vagrant/.bashrc"
 # If you are on Windows host, with Git checkout windows line terminator style CRLF
 # this comes in handy
 su - vagrant -c "dos2unix  /home/vagrant/.bashrc > /dev/null 2>&1"
+=======
+<<<<<<< HEAD
+su - vagrant -c "cp /vagrant/.bashrc /home/vagrant/.bashrc" 
+=======
```
Comment (alayek) [inline provision.sh]: Remove this.

**Comment by alayek** [comment]
Remove the merge conflict specific lines. By the way @abhisekp , I pulled from the branch in your forked repo - noticed some oddity. Like reappearance of already fixed issues. Or re-installation of stuff that was already moved within one single install statement.

Did you properly refresh your fork?

File: provision.sh (hunk 5 above)
Comment (koustuvsinha) [inline provision.sh]: yes @alayek we can remove it

Comment (alayek) [inline provision.sh]: Let the git cloud and fog clear up, I will remove it.

File: provision.sh (hunk 6 above)
Comment (abhisekp) [inline provision.sh]: i should have used atom to resolve the merge commits :pensive:

File: provision.sh (hunk 5 above)
Comment (byteknacker) [inline provision.sh]: @raisedadead @alayek please don't remove libpq-dev, this is needed for the proper installation of psycop2 within the virtualenv, otherwise Python will not interface with Postgres and nor will Heroku.

**Comment by byteknacker** [comment]
It passed all automated tests, my manual tests both with zeus.py and without. Now only asciinema somehow is causing troubles.

1__developer__vagrant__and_byteknacker_fcc-python-vagrant__vagrant_box_development_for_fcc_students_who_are_learning_python

**Comment by byteknacker** [comment]
I need to tests two things:
1. asciinema
2. run git logs to check everything so there are no errors left.

**Comment by byteknacker** [comment]
2 is fine: https://gist.github.com/byteknacker/7578a3f2ddabe47d0b56ce387d340343

**Comment by byteknacker** [comment]
1 is also fine please refer to: https://asciinema.org/a/11u0jwgtkuvwfcfo878kb1076

**Comment by byteknacker** [comment]
@alayek would you mind testing again and let me know about your errors. I cannot find any. Please merge this one if everyone is ok with testing. We can release Version 0.1.0 with this PR.

**Comment by byteknacker** [comment]
1__developer__vagrant__and_fixed_rebasing_for__34_by_abhisekp_ _pull_request__36_ _byteknacker_fcc-python-vagrant

**Comment by byteknacker** [comment]
I manually tested everything for the latest commit of this PR. LGTM.

**Comment by alayek** [comment]
I tested it all manually. 

Removal of `python-dev` would not harm anything. So approved.

Also tested for local git configuration setting. Noticed that once set, it didn't ask me for it again on second login.

# LGTM :+1:
